trigger:
- main

# strategy:
#  matrix:
#   linux:
#     operatingSystem: "ubuntu-latest"
#   mac:
#     operatingSystem: "macos-latest"

pool:
  vmImage: "ubuntu-latest"


stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the build!"


- stage: DevDeploy
  jobs:
  - deployment: DevDeployJob
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev

- stage: QADeploy
  jobs:
  - deployment: QADeployJob
    environment: QA
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev
          - script : echo Test coverage 90%
            displayName: "Coverage Results"
            
- stage: StaginDeploy
  jobs:
  - deployment: StagingDeployJob
    environment: Staging
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev





