trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  tag:  33

stages:

- stage: Build
  displayName: Build Docker Image & publish K8S files
  jobs:
  - job: Build
    displayName: Build & Push Docker image
    pool:
      vmImage: ubuntu-latest
    steps:
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     containerRegistry: 'pedroavpereiradev-docker-hub'
    #     repository: 'pedroavpereiradev/currency-exchange'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile'
    #     tags: '$(tag)'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.yaml'
        TargetFolder: '$(System.ArtifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      displayName: Publish K8S Files
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'manifests'
        publishLocation: 'Container'

- stage: Deploy
  displayName: Deploy Image to K8S
  jobs:
  - job: Deploy
    displayName: Deploy Docker Image
    pool:
      vmImage: "ubuntu-latest"
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download Artifacts
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactDirectory)'
    
    - task: KubernetesManifest@1
      displayName: K8s Deployment
      inputs:
        action: 'deploy'
        connectionType: 'kubernetesServiceConnection'
        kubernetesServiceConnection: 'azure-kubernetes-connection'
        namespace: 'default'
        manifests: '$(System.ArtifactDirectory)/configuration/kubernetes/deployment.yaml'
        containers: 'pedroavpereiradev/currency-exchange:$(tag)'
